In [58]:
import pandas as pd
import numpy as np

In [59]:
df=pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [60]:
df['brand'].nunique()

32

In [61]:
df['fuel'].nunique()

4

In [62]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [63]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

K-1 One hot coding

In [64]:
pd.get_dummies(df[['fuel','owner']],drop_first=True)

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,True,False,False,False,False,False,False
1,True,False,False,False,True,False,False
2,False,False,True,False,False,False,True
3,True,False,False,False,False,False,False
4,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...
8123,False,False,True,False,False,False,False
8124,True,False,False,True,False,False,False
8125,True,False,False,False,False,False,False
8126,True,False,False,False,False,False,False
8127,True,False,False,False,False,False,False

# One hot encoding using sklearn

In [65]:
from sklearn .model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)
x_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [66]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [67]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()
x_test_new=ohe.transform(x_test[['fuel','owner']]).toarray()

In [68]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 11)

In [69]:
x_train_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [70]:

ohe = OneHotEncoder(drop='first')
x_train_new = ohe.fit_transform(x_train[['fuel','owner']]).toarray()
x_test_new = ohe.transform(x_test[['fuel','owner']]).toarray()
x_train_new.shape

(6502, 7)

In [71]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 9)

One hot encoding With top catagories

In [72]:
counts=df['brand'].value_counts()

In [73]:
df.brand.nunique()
threshold=100

In [74]:
replace=counts[counts<=threshold].index
replace

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [ ]:
pd.get_dummies(df['brand'].replace(replace,'uncommon'))