In [34]:
import pandas as pd

In [35]:
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [36]:
pd.read_json("https://api.exchangerate-api.com/v4/latest/INR")

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.0383
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.6660
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.8520
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,3.8400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.1730
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.1970
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.2690
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-17,1778976001,0.2690

SQL data

In [37]:
import http.client

conn = http.client.HTTPSConnection("youtube138.p.rapidapi.com")

payload = "{\"id\":\"UCJ5v_MCY6GNUBTO8-D3XoAg\",\"filter\":\"videos_latest\",\"cursor\":\"\",\"hl\":\"en\",\"gl\":\"US\"}"

headers = {
    'x-rapidapi-key': "950436891fmshe6f5b5f23f2b2f1p113868jsn5f67ea95c10d",
    'x-rapidapi-host': "youtube138.p.rapidapi.com",
    'Content-Type': "application/json"
}

conn.request("POST", "/channel/videos/", payload, headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"contents":[{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":342,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/va9hE07C0OI\/mqdefault_6s.webp?du=3000&sqp=CNaeptAG&rs=AOn4CLAntiLR10eujYwlChls0E5I8_coQA","width":320}],"publishedTimeText":"7 hours ago","stats":{"views":46902},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/va9hE07C0OI\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB17uvPP0YCh-SZJoWWt3-bg0Ofdg","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/va9hE07C0OI\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAjkNzdAiI_tJ0fAsh9E4DjbURi9w","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/va9hE07C0OI\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCkS577PMjFs7OY2b7m6S0ZOPpfRQ","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/va9hE07C0OI\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCg6QAtEb5Z7k8WCcdmXY07-jYauQ","width":336}],"title":"El Grande Americano and Los Americanos engage \u201cOriginal\u201d and The Creeds: Lucha Libre AAA highlights","videoId":"va9hE07C0OI"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":183,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/MmTKDx-NbLA\/mqdefault_6s.webp?du=3000&sqp=CICqptAG&rs=AOn4CLAmdm_Fc8sHSWDNiLIV1wAitZ17VQ","width":320}],"publishedTimeText":"7 hours ago","stats":{"views":13462},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/MmTKDx-NbLA\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBV9EtiQGe7ujOjZLFvtKXBc7CHQw","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/MmTKDx-NbLA\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB-NGh7zLm1Bxcp90sW2_rrIjg91Q","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/MmTKDx-NbLA\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC1ytgXpesnGHjdxycD5AoXxSL2Gg","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/MmTKDx-NbLA\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCyuc5araRoSaQlbL1SJHf36Txdaw","width":336}],"title":"Mr. Iguana & La Parka win Fatal 4-Way Match, The War Raiders attack: Lucha Libre AAA highlights","videoId":"MmTKDx-NbLA"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":183,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/6dr4Os2snbk\/mqdefault_6s.webp?du=3000&sqp=CNClptAG&rs=AOn4CLBcyOSZkgPRu93CX40f53P-Tt_U6A","width":320}],"publishedTimeText":"7 hours ago","stats":{"views":7982},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/6dr4Os2snbk\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDJ54FpOj1JmmK4E0LLChh7KJDZmw","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/6dr4Os2snbk\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBAQDX1YO7mQPAVZEktpYGpllyFLA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/6dr4Os2snbk\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCp1oYTgLHDDOHQaPMWsdkvohKijg","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/6dr4Os2snbk\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC4P8MrMZD8hbUiwZOviJcyVCndLA","width":336}],"title":"Galeno del Mal eviscerates Chris Carter & Drago: Lucha Libre AAA highlights, May 16, 2026","videoId":"6dr4Os2snbk"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":563,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/vOFmHTW8Fw8\/mqdefault_6s.webp?du=3000&sqp=CLCbptAG&rs=AOn4CLCOIvo4tODMrfEPX6wxVexOgaGIwA","width":320}],"publishedTimeText":"15 hours ago","stats":{"views":197200},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/vOFmHTW8Fw8\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDOGDKgbMREbB4YwT0zpUrQmI46Iw","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/vOFmHTW8Fw8\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBMIk9efiuHQjiz1p3p5bjjq_HOQg","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/vOFmHTW8Fw8\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA5Lgl3Tb3Tizig1BIpbEJdD3jNoQ","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/vOFmHTW8Fw8\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBIJaLvIFKp8uFYzzqkYZHRZ3_Evg","width":336}],"title":"Top 10 Friday Night SmackDown moments: WWE Top 10, May 15, 2026","videoId":"vOFmHTW8Fw8"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":502,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/V3xPHYsB6ko\/mqdefault_6s.webp?du=3000&sqp=CPKwptAG&rs=AOn4CLBtQVx8qnNhkMfGSopWbomA9vEbOg","width":320}],"publishedTimeText":"18 hours ago","stats":{"views":25700},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/V3xPHYsB6ko\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB2zgkhAI0MyXvJ4t5GGbYDMuRMwA","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/V3xPHYsB6ko\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDaXBG9QvHdWf3ajQK1wskOK-GE1g","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/V3xPHYsB6ko\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDL2gmim5b5RkCmjGSUgARUuTX_KA","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/V3xPHYsB6ko\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqH6tHNtpLofTzOJKxYs0OzM1Qgg","width":336}],"title":"FULL MATCH: Alpha Academy vs. The Culling: WWE Main Event, May 14, 2026","videoId":"V3xPHYsB6ko"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":139,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/bQBRxlstcb4\/mqdefault_6s.webp?du=3000&sqp=CIayptAG&rs=AOn4CLBbC3l4tdhws65c4TyleTwipoEiaA","width":320}],"publishedTimeText":"20 hours ago","stats":{"views":27991},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/bQBRxlstcb4\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBjrj-jddH3dAg2Emz4ScRthqLCRw","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/bQBRxlstcb4\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBmk6VHKtcwnRy__wIWgozRgECewA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/bQBRxlstcb4\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYH_0OdPb4hCRhBhNAxdCkJfBkjQ","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/bQBRxlstcb4\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCW5W4jvZ0aAkt80dWsl7tjJtdnQA","width":336}],"title":"Bubba Ray dares PC Athlete to \u201cwant to hurt\u201d her opponent: WWE LFG","videoId":"bQBRxlstcb4"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":581,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/9Wm0LrscueU\/mqdefault_6s.webp?du=3000&sqp=CLGGptAG&rs=AOn4CLCZn8ifFBOMYRoCxhDTESCWlq4klg","width":320}],"publishedTimeText":"1 day ago","stats":{"views":594411},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/9Wm0LrscueU\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAEJKrNrBC7-5SLxPqTFcs7RVcHUg","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/9Wm0LrscueU\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAQV-oqyJZyJfCCok1Dy6gFziC7XA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/9Wm0LrscueU\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBFyzprtohcZy9vCOZyfg54MUxFdA","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/9Wm0LrscueU\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB2jvJfEm3Hu5cXeTNQZg2y1MB2xQ","width":336}],"title":"Full SmackDown highlights: May 15, 2026","videoId":"9Wm0LrscueU"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":240,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/md2Olnc3xv8\/mqdefault_6s.webp?du=3000&sqp=CM6tptAG&rs=AOn4CLDeE4H0r6IwGKZtWkD0LmeirT9Q2w","width":320}],"publishedTimeText":"1 day ago","stats":{"views":316995},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/md2Olnc3xv8\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB4yp0gAUkrKp4cnYyEfanjIF5rUA","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/md2Olnc3xv8\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLC8CAyiA1o6KTJqCuphHewE--EfKA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/md2Olnc3xv8\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDz6ZsbJ2UB8NPe18ztTMGbT7WnkQ","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/md2Olnc3xv8\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1k0U6XaGwEqEbzUKTjHepUD4pkA","width":336}],"title":"The MFTs prevent Royce Keys from beating Gunther: SmackDown highlights, May 15, 2026","videoId":"md2Olnc3xv8"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":210,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/sUJX7dMbsJk\/mqdefault_6s.webp?du=3000&sqp=CJiHptAG&rs=AOn4CLCC4KV-rfFCVqWrwu-bQGr-L1-Yfw","width":320}],"publishedTimeText":"1 day ago","stats":{"views":281764},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/sUJX7dMbsJk\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDXzfeScdmCnBflQVEJm15eo93-PQ","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/sUJX7dMbsJk\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDi0O6oBVQ4endfV5vVURKGToWkhA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/sUJX7dMbsJk\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCheYCOZHYn9gWMkcRNIzto8HYTzg","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/sUJX7dMbsJk\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQQcoXl7DA02YpjJDSa2uvi-5o8A","width":336}],"title":"Jade Cargill, Michin & B-Fab crush Charlotte Flair & Alexa Bliss: SmackDown highlights, May 15, 2026","videoId":"sUJX7dMbsJk"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":239,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/3fEGTbwEgn4\/mqdefault_6s.webp?du=3000&sqp=CMaxptAG&rs=AOn4CLD6W9TQnSolksFLxYZPEYH04-rY_g","width":320}],"publishedTimeText":"1 day ago","stats":{"views":193974},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/3fEGTbwEgn4\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAHMtN7Bh1f7c-K0MSOx2mWIPyn3w","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/3fEGTbwEgn4\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCj12ePWebTkCkbHJZs_WsrnfBYTw","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/3fEGTbwEgn4\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBv4mJ_qoExcRzikQm839oMsC1uiw","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/3fEGTbwEgn4\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnOuY5v7Mq_LH5EIoJMamg_5tgmQ","width":336}],"title":"Charlotte Flair and Alexa Bliss interrupt Jade Cargill: SmackDown highlights, May 15, 2026","videoId":"3fEGTbwEgn4"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":200,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/vOn1gM5fv2o\/mqdefault_6s.webp?du=3000&sqp=CMKSptAG&rs=AOn4CLDs27_BmaqWqWWQ6gkRWbnjtI9q4w","width":320}],"publishedTimeText":"1 day ago","stats":{"views":179380},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/vOn1gM5fv2o\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDgGVncyR6dYvyRgBvGp_I9-PBRkA","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/vOn1gM5fv2o\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAr-2JeEfLE19LNrBt-SNvzDAW-VA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/vOn1gM5fv2o\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCpY15Dbjj0cHXJI5htABrJYpKXzA","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/vOn1gM5fv2o\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCyX_Ryri21aJdg7wF3CMQFzVDw3Q","width":336}],"title":"Damian Priest defeats Tama Tonga: SmackDown highlights, May 15, 2026","videoId":"vOn1gM5fv2o"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":77,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/N5256fy_Yto\/mqdefault_6s.webp?du=3000&sqp=CM6tptAG&rs=AOn4CLAutqLaUTpzdfSifPGed6HZJo0amQ","width":320}],"publishedTimeText":"1 day ago","stats":{"views":181379},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/N5256fy_Yto\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAO5MwzKH4HwcAhumptiakC2sc8GQ","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/N5256fy_Yto\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBlFRCqf05qEM4ka0VavagJXmazWA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/N5256fy_Yto\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLABZysPJW_A9GJ7vEAcMnlUCoynlA","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/N5256fy_Yto\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDilOIP_HK3EDJ9Q85ngLoscRUR9Q","width":336}],"title":"Danhausen cooks up his next masterpiece: SmackDown highlights, May 15, 2026","videoId":"N5256fy_Yto"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":206,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/q7YtTHKXwY8\/mqdefault_6s.webp?du=3000&sqp=CKmnptAG&rs=AOn4CLC8YaSvwWBPCcSY1W-KoTpPuhN6QA","width":320}],"publishedTimeText":"1 day ago","stats":{"views":138840},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/q7YtTHKXwY8\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBbM795BCdy9gLNznBzCK8DmARq5A","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/q7YtTHKXwY8\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDAYPI6cLNzZ_VwLzAedyeErMsiWw","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/q7YtTHKXwY8\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAmyavZjKrf3tKllTj35p2MpnO3ow","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/q7YtTHKXwY8\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD_58RhW6Yg6LqHmEDXlsLMKGBaJQ","width":336}],"title":"Carmelo Hayes vs. Ricky Saints: SmackDown highlights, May 15, 2026","videoId":"q7YtTHKXwY8"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":634,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/YFHdUGyZKAo\/mqdefault_6s.webp?du=3000&sqp=CL6rptAG&rs=AOn4CLC2dxDLVbXi_o6M0WjxYndlmME43w","width":320}],"publishedTimeText":"1 day ago","stats":{"views":502628},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/YFHdUGyZKAo\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCceNJQGGXFwPQBE-QXAeYycoxLPA","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/YFHdUGyZKAo\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAhIVc5XhUoAZBukzK-UBsG313PJA","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/YFHdUGyZKAo\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAsyHwE8Xk111jtN1OPRruqaXLOfQ","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/YFHdUGyZKAo\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAYH2J633R4Jjw2NMfBBMU8GlhpYg","width":336}],"title":"FULL SEGMENT: Royce Keys ruins Gunther\u2019s contract signing with Cody Rhodes: SmackDown, May 15, 2026","videoId":"YFHdUGyZKAo"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":197,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/mTUcuzVV1Qs\/mqdefault_6s.webp?du=3000&sqp=CNOIptAG&rs=AOn4CLBCR-AXBSw9PBnJzPrfYKudSwUrog","width":320}],"publishedTimeText":"1 day ago","stats":{"views":210735},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/mTUcuzVV1Qs\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCAx3u2pRp1YgZGailZLOTIoAAECg","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/mTUcuzVV1Qs\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDiK4sgaJGwfipQgTkdCinbiVpHYg","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/mTUcuzVV1Qs\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBksYTI_nxWhGblsE3H70CaPzTEcg","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/mTUcuzVV1Qs\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCaUP3NsT3fo884JFT7vtEBCHMhAA","width":336}],"title":"Paige and Brie Bella dispatch Giulia and Kiana James: SmackDown highlights, May 15, 2026","videoId":"mTUcuzVV1Qs"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":111,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/fZJeXb2x3J8\/mqdefault_6s.webp?du=3000&sqp=CPuPptAG&rs=AOn4CLDrEgvN5-d-C4-KoobCirUvs-INMg","width":320}],"publishedTimeText":"1 day ago","stats":{"views":91338},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/fZJeXb2x3J8\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAgnQKNV8h9jEjt5voAZ13hZQSRWg","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/fZJeXb2x3J8\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBX8Ox0YyNYvPRK8eedpW5Vq_jS0A","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/fZJeXb2x3J8\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCaQf8qVQYezPNUlKSe_3WYe0AT2Q","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/fZJeXb2x3J8\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAATocPLCsWm3TqIicv_cYlsapbFA","width":336}],"title":"Trick Williams makes deafening hometown entrance: SmackDown highlights, May 15, 2026","videoId":"fZJeXb2x3J8"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":217,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/Xh-IQNILQno\/mqdefault_6s.webp?du=3000&sqp=CM6YptAG&rs=AOn4CLATtsBGWe8kS0fAzCxgeiNMn83gSQ","width":320}],"publishedTimeText":"1 day ago","stats":{"views":124165},"thumbnails":[{"height":94,"url":"https:\/\/i.ytimg.com\/vi\/Xh-IQNILQno\/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD_XITGX032jRULZJM8eyE1YGZaaA","width":168},{"height":110,"url":"https:\/\/i.ytimg.com\/vi\/Xh-IQNILQno\/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAsAS2M4o0hByRGrp17wqRZvbmppg","width":196},{"height":138,"url":"https:\/\/i.ytimg.com\/vi\/Xh-IQNILQno\/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQR1qUP-WSKGaPwyleodeVcM8xlg","width":246},{"height":188,"url":"https:\/\/i.ytimg.com\/vi\/Xh-IQNILQno\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD_w4WwTa7zAhL_YKOn_nx6FHHbtA","width":336}],"title":"Trick Williams earn big hometown win against The Miz: SmackDown highlights, May 15, 2026","videoId":"Xh-IQNILQno"}},{"type":"video","video":{"badges":[],"isLiveNow":false,"lengthSeconds":308,"movingThumbnails":[{"height":180,"url":"https:\/\/i.ytimg.com\/an_webp\/8nsCMc4wsMI\/mqdefault_6s.webp?du=3000&sqp=CNSUptAG&rs=AOn4CLCLNCqgbcgJO0_qWnCzYdzH4nDniQ","width":320}],"publishedTimeText":"1 day ago","stats":{"views":147566},"thumbnails":[{"height":94,"url":"https: