In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [24]:
df=pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [25]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [27]:
x_train.head()

    age  gender  fever   cough       city
67   65    Male   99.0    Mild  Bangalore
78   11    Male  100.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata
7    20  Female    NaN  Strong     Mumbai
48   66    Male   99.0  Strong  Bangalore

In [28]:
#adding simple imputer to fever column
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[["fever"]])


#also the test data
x_test_fever=si.transform(x_test[["fever"]])

x_train_fever.shape

(80, 1)

In [29]:
#ordinalencoden-> cough column
oe=OrdinalEncoder()
x_train_cough=oe.fit_transform(x_train[["cough"]])

# Also the test data
x_test_cough=oe.transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [30]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

x_train_city=ohe.fit_transform(x_train[["city",'gender']])
x_test_city=ohe.transform(x_test[["city",'gender']])

In [31]:
#extracting age column



x_train_age=x_train.drop(columns=["fever","gender","city","cough"]).values
x_test_age=x_test.drop(columns=["fever","gender","city","cough"]).values

In [34]:
x_train_transformed = np.concatenate([x_train_age, x_train_fever, x_train_cough, x_train_city], axis=1)
x_test_transformed=np.concatenate([x_test_age,x_test_fever,x_test_cough,x_test_city], axis=1)
x_train_transformed.shape

(80, 7)

In [ ]:
#from using column transformer
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ("tnf", SimpleImputer(), ["fever"]),
    ("tnc", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"]),
    ("tng", OneHotEncoder(sparse_output=False, drop='first'), ["gender", "city"])
], remainder="passthrough")
x_train_tran = transformer.fit_transform(x_train)
x_test_tran = transformer.transform(x_test)
x_train_tran.shape

(80, 7)